from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
from func import newLable1pg1
